"""Live Telegram adapter (python-telegram-bot).

Inbound: text (with `text_link` entities flattened to `[label](url)`), photos,
stickers and GIFs (all normalized to image; animated ones are converted to an
animated GIF locally, see `media.py`), replies, and albums (media groups, which
arrive as several Updates sharing a `media_group_id` and are reassembled into
one message). Outbound: text, single photo, a media-group album, an animation,
or audio (a bridged QQ voice note).

The `[label] name:` header is bolded via an explicit `MessageEntity` rather than
a parse_mode, so the body after it is never scanned for markup and needs no
escaping.
"""

from __future__ import annotations

import asyncio
import datetime
import itertools
import time
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from telegram import InputMediaPhoto, MessageEntity

from antares_bot.bot_logging import get_logger

from modules.tri_lug_utils import media
from modules.tri_lug_utils.adapters import BaseAdapter
from modules.tri_lug_utils.bridge_message import (
    TG,
    Attachment,
    BridgeMessage,
    BridgeUser,
    sniff_image_mime,
)
from modules.tri_lug_utils.header import render_header

if TYPE_CHECKING:
    from telegram import Message, Update, User
    from telegram.ext import Application

_LOGGER = get_logger(__name__)

# Telegram delivers an album as several Updates in quick succession; buffer them
# this long and flush as one bridged message.
_ALBUM_DEBOUNCE = 1.0

# Telegram caps a media group at 10 items.
_MEDIA_GROUP_MAX = 10

# Reuse a fetched profile photo this long before re-checking, so an avatar
# isn't refetched on every message but a changed one still propagates.
_AVATAR_TTL = 6 * 3600.0

# Converted animations are cached by `file_unique_id` (Telegram's stable content
# key) so a sticker that gets spammed is only ever converted once. Failures are
# cached too — a sticker that won't convert won't convert next time either, and
# retrying costs a subprocess on the latency-sensitive inbound path.
_ANIM_CACHE_MAX = 128

# Ceilings on `msg.animation` (a Telegram "GIF" is really a silent MP4, and can
# be minutes long). Over either limit the static thumbnail is bridged instead:
# a long MP4 makes a huge GIF, which is slow to produce, blows past QQ's image
# limits, and bloats the base64 payload on the QQ transport.
_GIF_MAX_SECONDS = 10.0
_GIF_MAX_BYTES = 5 * 1024 * 1024

# Ceiling on what a conversion may *produce*. A GIF past this would overrun QQ's
# image limits and bloat the base64 payload on the QQ transport.
_ANIM_MAX_OUTPUT_BYTES = 8 * 1024 * 1024


@dataclass
class _Album:
    user: "User"
    messages: list["Message"] = field(default_factory=list)
    task: asyncio.Task | None = None


class TelegramAdapter(BaseAdapter):
    platform = TG

    def __init__(self, room_key: str, chat_id: int) -> None:
        super().__init__(room_key)
        self.chat_id = chat_id
        self._app: "Application" | None = None
        self._albums: dict[str, _Album] = {}
        # tg user id -> (fetched_at, avatar_key|None, bytes|None)
        self._avatars: dict[int, tuple[float, str | None, bytes | None]] = {}
        # file_unique_id -> converted GIF bytes, or None for "known unconvertible"
        self._anims: OrderedDict[str, bytes | None] = OrderedDict()

    def attach_app(self, app: "Application") -> None:
        self._app = app

    async def stop(self) -> None:
        for album in self._albums.values():
            if album.task is not None:
                album.task.cancel()
        self._albums.clear()

    def matches(self, update: "Update") -> bool:
        """Filter for the bridged group; edits are ignored for now."""
        if update.edited_message is not None:
            return False
        chat = update.effective_chat
        msg = update.effective_message
        return msg is not None and chat is not None and chat.id == self.chat_id

    async def on_update(self, update: "Update") -> None:
        msg = update.effective_message
        user = update.effective_user
        if msg is None:
            return
        # Pin service message: mirror the pin onto the other platforms. Skip the
        # service message generated by our own pin write to avoid a loop.
        if msg.pinned_message is not None:
            own = (
                self._app is not None
                and user is not None
                and user.id == self._app.bot.id
            )
            if not own and self.router is not None:
                await self.router.pin(TG, str(msg.pinned_message.message_id))
            return
        if user is None:
            return
        # Loop prevention: never re-bridge the bridge bot's own messages.
        if self._app is not None and user.id == self._app.bot.id:
            return

        if msg.media_group_id is not None:
            self._buffer_album(msg.media_group_id, msg, user)
            return

        bm = await self._build_message(msg, user)
        if bm is not None:
            await self._emit(bm)

    async def set_pin(self, native_id: str, pinned: bool) -> None:
        if self._app is None:
            return
        try:
            mid = int(native_id)
        except ValueError:
            return
        if pinned:
            await self._app.bot.pin_chat_message(
                chat_id=self.chat_id, message_id=mid, disable_notification=True
            )
        else:
            await self._app.bot.unpin_chat_message(chat_id=self.chat_id, message_id=mid)

    # ------------------------------------------------------------------ albums
    def _buffer_album(self, gid: str, msg: "Message", user: "User") -> None:
        album = self._albums.get(gid)
        if album is None:
            album = _Album(user=user)
            self._albums[gid] = album
            album.task = asyncio.create_task(self._flush_album(gid))
        album.messages.append(msg)

    async def _flush_album(self, gid: str) -> None:
        try:
            await asyncio.sleep(_ALBUM_DEBOUNCE)
        except asyncio.CancelledError:
            return
        album = self._albums.pop(gid, None)
        if album is None or not album.messages:
            return
        msgs = sorted(album.messages, key=lambda m: m.message_id)
        first = msgs[0]
        # The caption rides on exactly one item; take whichever has it.
        caption_msg = next((m for m in msgs if (m.caption or m.text)), first)
        text = self._plain_text(caption_msg)
        reply_to = (
            str(first.reply_to_message.message_id) if first.reply_to_message else None
        )
        attachments: list[Attachment] = []
        for m in msgs:
            attachments.extend(await self._extract_attachments(m))
        if not text and not attachments:
            return
        sender = self._bridge_user(album.user)
        await self._attach_avatar(album.user, sender)
        await self._emit(
            BridgeMessage(
                platform=TG,
                room_key=self.room_key,
                msg_id=str(first.message_id),
                sender=sender,
                text=text,
                reply_to_msg_id=reply_to,
                attachments=attachments,
                raw=msgs,
            )
        )

    # ------------------------------------------------------------ single message
    async def _build_message(
        self, msg: "Message", user: "User"
    ) -> BridgeMessage | None:
        text = self._plain_text(msg)
        reply_to = (
            str(msg.reply_to_message.message_id) if msg.reply_to_message else None
        )
        attachments = await self._extract_attachments(msg)
        if not text and not attachments:
            return None
        sender = self._bridge_user(user)
        await self._attach_avatar(user, sender)
        return BridgeMessage(
            platform=TG,
            room_key=self.room_key,
            msg_id=str(msg.message_id),
            sender=sender,
            text=text,
            reply_to_msg_id=reply_to,
            attachments=attachments,
            raw=msg,
        )

    @staticmethod
    def _bridge_user(user: "User") -> BridgeUser:
        return BridgeUser(
            TG, str(user.id), user.full_name or user.username or str(user.id)
        )

    async def _attach_avatar(self, user: "User", bridge_user: BridgeUser) -> None:
        """Tag the sender with their profile photo (key + bytes) so a Matrix
        ghost can mirror it. Re-fetches at most once per TTL per user, and
        reuses cached bytes when the photo's unique id is unchanged."""
        if self._app is None:
            return
        cached = self._avatars.get(user.id)
        now = time.monotonic()
        if cached is not None and now - cached[0] < _AVATAR_TTL:
            _, key, data = cached
            if key:
                bridge_user.avatar_key = key
                if data:
                    bridge_user.avatar_data = data
            return
        key: str | None = None
        data: bytes | None = None
        try:
            photos = await self._app.bot.get_user_profile_photos(user.id, limit=1)
            if photos.total_count and photos.photos:
                size = photos.photos[0][-1]  # largest of the first photo
                key = f"tg:{size.file_unique_id}"
                if cached is not None and cached[1] == key and cached[2]:
                    data = cached[2]  # unchanged photo — reuse cached bytes
                else:
                    data = await self._download(size)
        except Exception:
            _LOGGER.warning("[tg] failed to fetch avatar", exc_info=True)
        self._avatars[user.id] = (now, key, data)
        if key:
            bridge_user.avatar_key = key
            if data:
                bridge_user.avatar_data = data

    def _plain_text(self, msg: "Message") -> str:
        if msg.text is not None:
            return self._render_links(msg.text, msg.entities)
        if msg.caption is not None:
            return self._render_links(msg.caption, msg.caption_entities)
        return ""

    @staticmethod
    def _render_links(text: str, entities) -> str:
        """Flatten `text_link` entities into `[label](url)`, leaving everything
        else untouched. Entity offsets/lengths are UTF-16 code units, so the
        slicing is done on the UTF-16-LE encoding to stay correct across
        emoji / non-BMP characters."""
        links = [
            e for e in (entities or []) if e.type == MessageEntity.TEXT_LINK and e.url
        ]
        if not links:
            return text
        u16 = text.encode("utf-16-le")
        links.sort(key=lambda e: e.offset)
        out: list[str] = []
        cursor = 0  # in UTF-16 code units
        for e in links:
            start, end = e.offset, e.offset + e.length
            if start < cursor:  # overlapping/nested; skip to stay well-formed
                continue
            out.append(u16[cursor * 2 : start * 2].decode("utf-16-le"))
            label = u16[start * 2 : end * 2].decode("utf-16-le")
            out.append(f"[{label}]({e.url})")
            cursor = end
        out.append(u16[cursor * 2 :].decode("utf-16-le"))
        return "".join(out)

    async def _extract_attachments(self, msg: "Message") -> list[Attachment]:
        """Photos, stickers and GIFs, all normalized to image Attachments.

        Animated stickers (`.tgs` Lottie), video stickers (`.webm`) and GIFs
        (`msg.animation`, really a silent MP4) are converted to an animated GIF
        here on the inbound path, so QQ and Matrix each receive the same moving
        bytes (see docs/design.md §2, Stickers). Conversion happens before the
        Router's fan, which hands the *same* BridgeMessage to every target — so
        one conversion serves both, and no adapter has to mutate shared state.

        Every conversion failure degrades to the static thumbnail rather than
        dropping anything."""
        out: list[Attachment] = []
        if msg.photo:
            data = await self._download(msg.photo[-1])
            if data is not None:
                out.append(
                    Attachment(
                        "image", data=data, mime="image/jpeg", filename="image.jpg"
                    )
                )
        if msg.sticker:
            st = msg.sticker
            if st.is_animated:
                out.extend(await self._animated(st, "tgs", "sticker"))
            elif st.is_video:
                out.extend(await self._animated(st, "webm", "sticker"))
            else:
                data = await self._download(st)
                if data is not None:
                    out.append(
                        Attachment(
                            "image",
                            data=data,
                            mime="image/webp",
                            filename="sticker.webp",
                        )
                    )
        if msg.animation:
            out.extend(await self._animated(msg.animation, "mp4", "animation"))
        return out

    async def _animated(self, obj, fmt: str, label: str) -> list[Attachment]:
        """Convert one animated Telegram object to a GIF Attachment, falling
        back to its static thumbnail on any failure. Returns 0 or 1 items."""
        if fmt == "mp4" and not self._within_gif_limits(obj):
            return await self._thumbnail(obj, label)

        key = obj.file_unique_id
        if key in self._anims:
            self._anims.move_to_end(key)
            gif = self._anims[key]
        else:
            gif = await self._convert(obj, fmt)
            self._anims[key] = gif
            self._anims.move_to_end(key)
            while len(self._anims) > _ANIM_CACHE_MAX:
                self._anims.popitem(last=False)

        if gif is None:
            _LOGGER.warning(
                "[tg] could not animate %s (%s), bridging static thumbnail", label, fmt
            )
            return await self._thumbnail(obj, label)
        return [
            Attachment("image", data=gif, mime="image/gif", filename=f"{label}.gif")
        ]

    async def _convert(self, obj, fmt: str) -> bytes | None:
        data = await self._download(obj)
        if data is None:
            return None
        if fmt == "tgs":
            gif = await media.tgs_to_gif(data)
        else:
            gif = await media.video_to_gif(data, fmt)
        if gif is None:
            return None
        # Sanity-check what came back rather than trusting the exit code: a
        # single-frame result is worse than the thumbnail (it costs bandwidth
        # and still doesn't move), and an oversized one would overrun QQ's image
        # limits and bloat the base64 payload on the QQ transport.
        if len(gif) > _ANIM_MAX_OUTPUT_BYTES:
            _LOGGER.warning("[tg] converted %s is %d bytes, too large", fmt, len(gif))
            return None
        if not media.is_animated_image(gif):
            _LOGGER.warning("[tg] converted %s came back with a single frame", fmt)
            return None
        return gif

    @staticmethod
    def _within_gif_limits(anim) -> bool:
        """A Telegram GIF is an arbitrary silent MP4; only convert short, small
        ones (see `_GIF_MAX_SECONDS` / `_GIF_MAX_BYTES`)."""
        size = getattr(anim, "file_size", None)
        if size is not None and size > _GIF_MAX_BYTES:
            return False
        duration = getattr(anim, "duration", None)
        if isinstance(duration, datetime.timedelta):
            duration = duration.total_seconds()
        return not (duration is not None and duration > _GIF_MAX_SECONDS)

    async def _thumbnail(self, obj, label: str) -> list[Attachment]:
        """The static-frame fallback: whatever preview Telegram already has.

        The mime is sniffed rather than assumed: a Telegram sticker thumbnail is
        WEBP *or* JPEG, and mislabelling a WEBP as JPEG makes Matrix clients
        refuse to render it."""
        thumb = getattr(obj, "thumbnail", None)
        if thumb is None:
            return []
        data = await self._download(thumb)
        if data is None:
            return []
        mime = sniff_image_mime(data) or "image/jpeg"
        ext = {"image/webp": "webp", "image/png": "png"}.get(mime, "jpg")
        return [Attachment("image", data=data, mime=mime, filename=f"{label}.{ext}")]

    @staticmethod
    def _media_src(att: Attachment):
        """bytes or url for sending; non-None is guaranteed by the caller's
        image filter (`a.data is not None or a.url`)."""
        src = att.data if att.data is not None else att.url
        assert src is not None
        return src

    async def _download(self, tg_obj) -> bytes | None:
        try:
            f = await tg_obj.get_file()
            return bytes(await f.download_as_bytearray())
        except Exception:
            _LOGGER.warning("[tg] failed to download media", exc_info=True)
            return None

    # ----------------------------------------------------------------- outbound
    @staticmethod
    def _caption(msg: BridgeMessage) -> tuple[str, list[MessageEntity]]:
        """Render the outbound text as `header\\nbody` plus the entity that bolds
        the header (`[QQ] name:` — the colon included).

        An explicit entity is used instead of parse_mode="HTML"/Markdown so the
        body is passed through verbatim: bridged text routinely contains `_`,
        `*`, `[text](url)` and raw `<`, all of which would need escaping (and
        would break) under a parse mode. The entity offset/length are UTF-16 code
        units, like every Telegram offset."""
        header = render_header(msg, TG)
        text = header + (f"\n{msg.text}" if msg.text else "")
        length = len(header.encode("utf-16-le")) // 2
        return text, [MessageEntity(MessageEntity.BOLD, offset=0, length=length)]

    async def send(
        self, msg: BridgeMessage, reply_to_native_id: str | None
    ) -> list[str]:
        if self._app is None:
            _LOGGER.warning("[tg.send] app not attached, dropping message")
            return []
        reply_id = int(reply_to_native_id) if reply_to_native_id else None
        caption, entities = self._caption(msg)
        images = [
            a
            for a in msg.attachments
            if a.kind == "image" and (a.data is not None or a.url)
        ]
        audios = [
            a
            for a in msg.attachments
            if a.kind == "audio" and (a.data is not None or a.url)
        ]

        if not images and not audios:
            sent = await self._app.bot.send_message(
                chat_id=self.chat_id,
                text=caption,
                entities=entities,
                reply_to_message_id=reply_id,
            )
            return [str(sent.message_id)]

        # Whichever media leg goes first carries the caption and the reply; every
        # produced id is returned (in order, first = reply anchor) so the Router
        # links each one.
        #
        # Images are walked in source order and consecutive stills are batched
        # into albums, but an animation always goes out alone: `sendMediaGroup`
        # only accepts photo/video/audio/document, so an animation physically
        # cannot ride in an album. Partitioning stills from animations instead
        # would be simpler but would reorder the sender's images.
        ids: list[str] = []
        for animated, group in itertools.groupby(images, key=self._is_animated):
            run = list(group)
            if animated:
                for att in run:
                    ids.append(
                        await self._send_animation(
                            att, caption, entities, reply_id, first=not ids
                        )
                    )
            else:
                ids.extend(
                    await self._send_images(
                        run, caption, entities, reply_id, first=not ids
                    )
                )
        for audio in audios:
            ids.append(
                await self._send_audio(
                    audio, caption, entities, reply_id, first=not ids
                )
            )
        return ids

    @staticmethod
    def _is_animated(att: Attachment) -> bool:
        """Whether this image has to go out via `send_animation`.

        `send_photo` re-encodes its input into a static JPEG, so a GIF sent that
        way arrives frozen. Two narrowing conditions:

        * The format must be GIF. `sendAnimation` takes only GIF or silent MP4,
          so an animated WebP or APNG (a QQ `mface` can be either) would be
          rejected outright — losing the message. Those keep going through
          `send_photo`: still, as today, but delivered.
        * Within GIF the call is made on the bytes, not the mime, because a
          *still* GIF pushed through `send_animation` becomes an animation
          bubble that cannot play. A url-only attachment has no bytes to
          inspect, so there the mime is all there is to go on."""
        mime = att.mime or sniff_image_mime(att.data)
        if mime != "image/gif":
            return False
        if att.data is None:
            return True
        return media.is_animated_image(att.data)

    async def _send_images(
        self,
        images: list[Attachment],
        caption: str,
        entities: list[MessageEntity],
        reply_id: int | None,
        *,
        first: bool,
    ) -> list[str]:
        """Send a run of still images. `first` means this run opens the whole
        outbound message, so it owns the caption and the reply anchor."""
        assert self._app is not None
        bot = self._app.bot
        if len(images) == 1:
            sent = await bot.send_photo(
                chat_id=self.chat_id,
                photo=self._media_src(images[0]),
                caption=caption if first else None,
                caption_entities=entities if first else None,
                reply_to_message_id=reply_id if first else None,
            )
            return [str(sent.message_id)]

        # Multiple images -> media-group album(s); caption on the first item.
        # The first batch carries the reply + caption.
        ids: list[str] = []
        for batch_start in range(0, len(images), _MEDIA_GROUP_MAX):
            batch = images[batch_start : batch_start + _MEDIA_GROUP_MAX]
            leads = first and batch_start == 0
            group = [
                InputMediaPhoto(
                    media=self._media_src(img),
                    caption=caption if (leads and i == 0) else None,
                    caption_entities=entities if (leads and i == 0) else None,
                )
                for i, img in enumerate(batch)
            ]
            sent_msgs = await bot.send_media_group(
                chat_id=self.chat_id,
                media=group,
                reply_to_message_id=reply_id if leads else None,
            )
            ids.extend(str(m.message_id) for m in sent_msgs)
        return ids

    async def _send_animation(
        self,
        att: Attachment,
        caption: str,
        entities: list[MessageEntity],
        reply_id: int | None,
        *,
        first: bool,
    ) -> str:
        """Send one animated image. `send_animation` rather than `send_photo`:
        the latter re-encodes to a static JPEG and kills the animation."""
        assert self._app is not None
        sent = await self._app.bot.send_animation(
            chat_id=self.chat_id,
            animation=self._media_src(att),
            # NOT `att.filename`. Telegram picks the media type off the upload's
            # filename extension, and the source name rarely has a usable one:
            # NapCat names its files after a content hash (`<hash>.image`, or no
            # extension at all) and a Matrix event may only carry `body`. Given
            # anything but `.gif`/`.mp4` here, `sendAnimation` degrades to a
            # document and the animation arrives as a file bubble. `_is_animated`
            # has already proven these bytes are an animated GIF, so the
            # extension is established fact, not a guess.
            filename="animation.gif",
            caption=caption if first else None,
            caption_entities=entities if first else None,
            reply_to_message_id=reply_id if first else None,
        )
        if getattr(sent, "animation", None) is None:
            # Telegram accepted the upload but declined to treat it as an
            # animation (it converts GIF -> MP4 server-side and can refuse).
            # Delivered, but as a file bubble — worth a line, since nothing else
            # surfaces it.
            _LOGGER.warning(
                "[tg] send_animation produced a non-animation message (%s bytes,"
                " %s); it will show as a file",
                len(att.data) if att.data is not None else "url",
                att.mime,
            )
        return str(sent.message_id)

    async def _send_audio(
        self,
        audio: Attachment,
        caption: str,
        entities: list[MessageEntity],
        reply_id: int | None,
        *,
        first: bool,
    ) -> str:
        """Send one audio attachment (a bridged QQ voice note, transcoded to mp3
        by the relay). `send_audio` rather than `send_voice`: the latter only
        accepts OGG/OPUS and rejects everything else."""
        assert self._app is not None
        sent = await self._app.bot.send_audio(
            chat_id=self.chat_id,
            audio=self._media_src(audio),
            filename=audio.filename or "voice.mp3",
            caption=caption if first else None,
            caption_entities=entities if first else None,
            reply_to_message_id=reply_id if first else None,
        )
        return str(sent.message_id)
