"""Live Telegram adapter (python-telegram-bot).

Inbound: text (with `text_link` entities flattened to `[label](url)`), photos and
stickers (normalized to image), replies, and albums (media groups, which arrive
as several Updates sharing a `media_group_id` and are reassembled into one
message). Outbound: text, single photo, or a media-group album.
"""

from __future__ import annotations

import asyncio
import time
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from telegram import InputMediaPhoto, MessageEntity

from antares_bot.bot_logging import get_logger

from modules.tri_lug_utils.adapters import BaseAdapter
from modules.tri_lug_utils.bridge_message import (
    TG,
    Attachment,
    BridgeMessage,
    BridgeUser,
)

if TYPE_CHECKING:
    from telegram import Message, Update, User
    from telegram.ext import Application

_LOGGER = get_logger(__name__)

# How messages from other platforms are labelled when rendered into Telegram.
_PLATFORM_LABEL = {"qq": "QQ", "matrix": "Matrix", "tg": "TG"}

# Telegram delivers an album as several Updates in quick succession; buffer them
# this long and flush as one bridged message.
_ALBUM_DEBOUNCE = 1.0

# Telegram caps a media group at 10 items.
_MEDIA_GROUP_MAX = 10

# Reuse a fetched profile photo this long before re-checking, so an avatar
# isn't refetched on every message but a changed one still propagates.
_AVATAR_TTL = 6 * 3600.0


@dataclass
class _Album:
    user: "User"
    messages: list["Message"] = field(default_factory=list)
    task: asyncio.Task | None = None


class TelegramAdapter(BaseAdapter):
    platform = TG

    def __init__(self, room_key: str, chat_id: int) -> None:
        super().__init__(room_key)
        self.chat_id = chat_id
        self._app: "Application" | None = None
        self._albums: dict[str, _Album] = {}
        # tg user id -> (fetched_at, avatar_key|None, bytes|None)
        self._avatars: dict[int, tuple[float, str | None, bytes | None]] = {}

    def attach_app(self, app: "Application") -> None:
        self._app = app

    async def stop(self) -> None:
        for album in self._albums.values():
            if album.task is not None:
                album.task.cancel()
        self._albums.clear()

    def matches(self, update: "Update") -> bool:
        """Filter for the bridged group; edits are ignored for now."""
        if update.edited_message is not None:
            return False
        chat = update.effective_chat
        msg = update.effective_message
        return msg is not None and chat is not None and chat.id == self.chat_id

    async def on_update(self, update: "Update") -> None:
        msg = update.effective_message
        user = update.effective_user
        if msg is None:
            return
        # Pin service message: mirror the pin onto the other platforms. Skip the
        # service message generated by our own pin write to avoid a loop.
        if msg.pinned_message is not None:
            own = (
                self._app is not None
                and user is not None
                and user.id == self._app.bot.id
            )
            if not own and self.router is not None:
                await self.router.pin(TG, str(msg.pinned_message.message_id))
            return
        if user is None:
            return
        # Loop prevention: never re-bridge the bridge bot's own messages.
        if self._app is not None and user.id == self._app.bot.id:
            return

        if msg.media_group_id is not None:
            self._buffer_album(msg.media_group_id, msg, user)
            return

        bm = await self._build_message(msg, user)
        if bm is not None:
            await self._emit(bm)

    async def set_pin(self, native_id: str, pinned: bool) -> None:
        if self._app is None:
            return
        try:
            mid = int(native_id)
        except ValueError:
            return
        if pinned:
            await self._app.bot.pin_chat_message(
                chat_id=self.chat_id, message_id=mid, disable_notification=True
            )
        else:
            await self._app.bot.unpin_chat_message(chat_id=self.chat_id, message_id=mid)

    # ------------------------------------------------------------------ albums
    def _buffer_album(self, gid: str, msg: "Message", user: "User") -> None:
        album = self._albums.get(gid)
        if album is None:
            album = _Album(user=user)
            self._albums[gid] = album
            album.task = asyncio.create_task(self._flush_album(gid))
        album.messages.append(msg)

    async def _flush_album(self, gid: str) -> None:
        try:
            await asyncio.sleep(_ALBUM_DEBOUNCE)
        except asyncio.CancelledError:
            return
        album = self._albums.pop(gid, None)
        if album is None or not album.messages:
            return
        msgs = sorted(album.messages, key=lambda m: m.message_id)
        first = msgs[0]
        # The caption rides on exactly one item; take whichever has it.
        caption_msg = next((m for m in msgs if (m.caption or m.text)), first)
        text = self._plain_text(caption_msg)
        reply_to = (
            str(first.reply_to_message.message_id) if first.reply_to_message else None
        )
        attachments: list[Attachment] = []
        for m in msgs:
            attachments.extend(await self._extract_attachments(m))
        if not text and not attachments:
            return
        sender = self._bridge_user(album.user)
        await self._attach_avatar(album.user, sender)
        await self._emit(
            BridgeMessage(
                platform=TG,
                room_key=self.room_key,
                msg_id=str(first.message_id),
                sender=sender,
                text=text,
                reply_to_msg_id=reply_to,
                attachments=attachments,
                raw=msgs,
            )
        )

    # ------------------------------------------------------------ single message
    async def _build_message(
        self, msg: "Message", user: "User"
    ) -> BridgeMessage | None:
        text = self._plain_text(msg)
        reply_to = (
            str(msg.reply_to_message.message_id) if msg.reply_to_message else None
        )
        attachments = await self._extract_attachments(msg)
        if not text and not attachments:
            return None
        sender = self._bridge_user(user)
        await self._attach_avatar(user, sender)
        return BridgeMessage(
            platform=TG,
            room_key=self.room_key,
            msg_id=str(msg.message_id),
            sender=sender,
            text=text,
            reply_to_msg_id=reply_to,
            attachments=attachments,
            raw=msg,
        )

    @staticmethod
    def _bridge_user(user: "User") -> BridgeUser:
        return BridgeUser(
            TG, str(user.id), user.full_name or user.username or str(user.id)
        )

    async def _attach_avatar(self, user: "User", bridge_user: BridgeUser) -> None:
        """Tag the sender with their profile photo (key + bytes) so a Matrix
        ghost can mirror it. Re-fetches at most once per TTL per user, and
        reuses cached bytes when the photo's unique id is unchanged."""
        if self._app is None:
            return
        cached = self._avatars.get(user.id)
        now = time.monotonic()
        if cached is not None and now - cached[0] < _AVATAR_TTL:
            _, key, data = cached
            if key:
                bridge_user.avatar_key = key
                if data:
                    bridge_user.avatar_data = data
            return
        key: str | None = None
        data: bytes | None = None
        try:
            photos = await self._app.bot.get_user_profile_photos(user.id, limit=1)
            if photos.total_count and photos.photos:
                size = photos.photos[0][-1]  # largest of the first photo
                key = f"tg:{size.file_unique_id}"
                if cached is not None and cached[1] == key and cached[2]:
                    data = cached[2]  # unchanged photo — reuse cached bytes
                else:
                    data = await self._download(size)
        except Exception:
            _LOGGER.warning("[tg] failed to fetch avatar", exc_info=True)
        self._avatars[user.id] = (now, key, data)
        if key:
            bridge_user.avatar_key = key
            if data:
                bridge_user.avatar_data = data

    def _plain_text(self, msg: "Message") -> str:
        if msg.text is not None:
            return self._render_links(msg.text, msg.entities)
        if msg.caption is not None:
            return self._render_links(msg.caption, msg.caption_entities)
        return ""

    @staticmethod
    def _render_links(text: str, entities) -> str:
        """Flatten `text_link` entities into `[label](url)`, leaving everything
        else untouched. Entity offsets/lengths are UTF-16 code units, so the
        slicing is done on the UTF-16-LE encoding to stay correct across
        emoji / non-BMP characters."""
        links = [
            e for e in (entities or []) if e.type == MessageEntity.TEXT_LINK and e.url
        ]
        if not links:
            return text
        u16 = text.encode("utf-16-le")
        links.sort(key=lambda e: e.offset)
        out: list[str] = []
        cursor = 0  # in UTF-16 code units
        for e in links:
            start, end = e.offset, e.offset + e.length
            if start < cursor:  # overlapping/nested; skip to stay well-formed
                continue
            out.append(u16[cursor * 2 : start * 2].decode("utf-16-le"))
            label = u16[start * 2 : end * 2].decode("utf-16-le")
            out.append(f"[{label}]({e.url})")
            cursor = end
        out.append(u16[cursor * 2 :].decode("utf-16-le"))
        return "".join(out)

    async def _extract_attachments(self, msg: "Message") -> list[Attachment]:
        """v1: photos and stickers, both normalized to a single image
        Attachment. Animated/video stickers use their static thumbnail to avoid
        lottie/webm conversion (see design doc §4)."""
        out: list[Attachment] = []
        if msg.photo:
            data = await self._download(msg.photo[-1])
            if data is not None:
                out.append(
                    Attachment(
                        "image", data=data, mime="image/jpeg", filename="image.jpg"
                    )
                )
        if msg.sticker:
            st = msg.sticker
            if st.is_animated or st.is_video:
                if st.thumbnail is not None:
                    data = await self._download(st.thumbnail)
                    if data is not None:
                        out.append(
                            Attachment(
                                "image",
                                data=data,
                                mime="image/jpeg",
                                filename="sticker.jpg",
                            )
                        )
            else:
                data = await self._download(st)
                if data is not None:
                    out.append(
                        Attachment(
                            "image",
                            data=data,
                            mime="image/webp",
                            filename="sticker.webp",
                        )
                    )
        return out

    @staticmethod
    def _media_src(att: Attachment):
        """bytes or url for sending; non-None is guaranteed by the caller's
        image filter (`a.data is not None or a.url`)."""
        src = att.data if att.data is not None else att.url
        assert src is not None
        return src

    async def _download(self, tg_obj) -> bytes | None:
        try:
            f = await tg_obj.get_file()
            return bytes(await f.download_as_bytearray())
        except Exception:
            _LOGGER.warning("[tg] failed to download media", exc_info=True)
            return None

    # ----------------------------------------------------------------- outbound
    async def send(
        self, msg: BridgeMessage, reply_to_native_id: str | None
    ) -> str | None:
        if self._app is None:
            _LOGGER.warning("[tg.send] app not attached, dropping message")
            return None
        bot = self._app.bot
        label = _PLATFORM_LABEL.get(msg.platform, msg.platform)
        reply_id = int(reply_to_native_id) if reply_to_native_id else None
        caption = f"[{label}] {msg.sender.display_name}:" + (
            f"\n{msg.text}" if msg.text else ""
        )
        images = [
            a
            for a in msg.attachments
            if a.kind == "image" and (a.data is not None or a.url)
        ]

        if not images:
            sent = await bot.send_message(
                chat_id=self.chat_id, text=caption, reply_to_message_id=reply_id
            )
            return str(sent.message_id)

        if len(images) == 1:
            sent = await bot.send_photo(
                chat_id=self.chat_id,
                photo=self._media_src(images[0]),
                caption=caption,
                reply_to_message_id=reply_id,
            )
            return str(sent.message_id)

        # Multiple images -> media-group album(s); caption on the first item.
        # The first batch carries the reply + caption and provides the primary id.
        primary: str | None = None
        for batch_start in range(0, len(images), _MEDIA_GROUP_MAX):
            batch = images[batch_start : batch_start + _MEDIA_GROUP_MAX]
            media = [
                InputMediaPhoto(
                    media=self._media_src(img),
                    caption=caption if (batch_start == 0 and i == 0) else None,
                )
                for i, img in enumerate(batch)
            ]
            sent_msgs = await bot.send_media_group(
                chat_id=self.chat_id,
                media=media,
                reply_to_message_id=reply_id if batch_start == 0 else None,
            )
            if primary is None and sent_msgs:
                primary = str(sent_msgs[0].message_id)
        return primary
